services:
  db:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      TZ: Asia/Ho_Chi_Minh
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 5s
      timeout: 5s
      retries: 10
  backend:
    image: anhtu2808/veganlife:latest
    build:
      dockerfile: Dockerfile
    container_name: veganlife
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - /var/docker/veganlife/credentials.json:/app/credentials.json
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  mysql_data: