name: CI/CD veganlife

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B clean package -DskipTests
        working-directory: ./identity-service

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ vars.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ vars.DOCKER_USERNAME }}/veganlife:latest
        working-directory: ./identity-service

      - name: Push Docker image
        run: docker push ${{ vars.DOCKER_USERNAME }}/veganlife:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: TEST
    steps:
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.HOST_IP }}
          username: root
          key: ${{ secrets.SECRET_KEY }}
          script: |
            cd /var/docker/veganlife
            echo "Deploying TEST environment..."
            docker compose pull
            docker compose down --remove-orphans || true
            docker rm -f $(docker ps -a -q --filter "name=veganlife") || true
            docker image prune -f
            docker compose up -d
            docker rmi $(docker images -q --filter "dangling=true") || true
            docker ps



    
        

